apiVersion: v1
kind: Service
metadata:
  name: football-league-api-service
  namespace: football
spec:
  type: NodePort
  selector:
    app: football-league-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
